MIDI_GCD_TIME = 128
MIDI_MAX_LEN = 163840
MIDI_ARRAY_MAX_LEN = MIDI_MAX_LEN // MIDI_GCD_TIME
MIDI_MAX_NOTE = 84
MIDI_MIN_NOTE = 31
MIDI_TOP_NOTE = MIDI_MAX_NOTE + 8
MIDI_BOTTOM_NOTE = MIDI_MIN_NOTE - 7
MIDI_NOTE_RANGE = MIDI_TOP_NOTE - MIDI_BOTTOM_NOTE